@
CREATE DATABASE IF NOT EXISTS developer_training_db;
USE developer_training_db;

CREATE TABLE IF NOT EXISTS Usuarios (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(100) NOT NULL,
    EDAD INT,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Niveles (
    ID_NIVELES VARCHAR(50) PRIMARY KEY,
    SECCION VARCHAR(100),
    NUMERO_NIVEL INT
);

CREATE TABLE IF NOT EXISTS Preguntas (
    ID_PREGUNTA INT AUTO_INCREMENT PRIMARY KEY,
    PREGUNTA TEXT NOT NULL,
    RESPUESTA TEXT NOT NULL,
    TIPO VARCHAR(50),
    ID_NIVEL VARCHAR(50),
    FOREIGN KEY (ID_NIVEL) REFERENCES Niveles(ID_NIVELES)
);

CREATE TABLE IF NOT EXISTS Estadisticas (
    ID_ESTADISTICAS VARCHAR(50) PRIMARY KEY,
    ID_USUARIO INT,
    NIVELES_COMPLETADOS TEXT,
    TIEMPO_TOTAL_JUEGO INT DEFAULT 0,
    RACHAS INT DEFAULT 0,
    ULTIMO_NIVEL_JUGADO VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID_USUARIO),
    FOREIGN KEY (ULTIMO_NIVEL_JUGADO) REFERENCES Niveles(ID_NIVELES)
);

INSERT INTO Usuarios (NOMBRE, EMAIL, CONTRASENA, EDAD) 
VALUES ('Usuario de Prueba', 'test@test.com', '1234', 25);
