
CREATE DATABASE IF NOT EXISTS developer_training_db;
USE developer_training_db;

CREATE TABLE IF NOT EXISTS Usuarios (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(100) NOT NULL,
    EDAD INT
);

CREATE TABLE IF NOT EXISTS Estadisticas (
    ID_USUARIO INT,
    NIVELES_COMPLETADOS TEXT,
    TIEMPO_TOTAL_JUEGO INT DEFAULT 0,
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID_USUARIO)
);

INSERT INTO Usuarios (NOMBRE, EMAIL, CONTRASENA, EDAD) 
VALUES ('Usuario de Prueba', 'test@test.com', '1234', 25);
